SET @HOUR = -1; -- 변수 설정 --
SELECT (@HOUR := @HOUR + 1) AS HOUR, -- 변수값을 1씩 증가시켜 0부터 23까지 --
(SELECT COUNT(HOUR(DATETIME)) FROM ANIMAL_OUTS WHERE HOUR(DATETIME)=@HOUR) AS COUNT --시간에 따라 카운트--
FROM ANIMAL_OUTS
WHERE @HOUR < 23;