SELECT DISTINCT(CART_PRODUCTS.CART_ID) --중복 제거--
FROM CART_PRODUCTS,
(SELECT CART_ID --우선 우유를 담은 카트를 선별하고--
FROM CART_PRODUCTS
WHERE NAME = '우유') AS MILK_IN_CART 
WHERE CART_PRODUCTS.CART_ID = MILK_IN_CART.CART_ID AND NAME = '요거트' --똑같은 카트에서 요거트도 담은 카트를 선별한다.--
ORDER BY CART_ID